name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build release APKs
        run: ./gradlew assembleRelease

      - name: Extract versionName
        run: echo "VERSION=$(grep versionName app/build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/*.apk
